Vous pouvez vous abonner à cet agenda public [[https://cloud.eig-forever.org/index.php/apps/calendar/p/C1YPGSGZ1JZPVDDU/EIG2018-Open][en ligne]].

* 1ère rencontres autour du libre dans l’administration lors du Paris Open Source Summit
  SCHEDULED: <2018-12-06 jeu. 9:00-18:00>
  :PROPERTIES:
  :LOCATION: 87, avenue des magasins généraux 93300 Aubervilliers (Dock Pullmann)
  :ID:       0cf649b9-04c8-45fc-a356-9364898ff069
  :END:

Vous êtes développeur ou développeuse dans le secteur public -
titulaire, contractuel ou prestataire - Vous êtes invités aux
premières rencontres des développeurs de l’administration qui ont pour
objectif de favoriser l’émergence d’une communauté autour de code
utilisé et produit par l’administration.

Au programme : découverte de la politique de contribution aux
logiciels libres de l’État et lightning talks pour découvrir les
projets menés au sein de l'administration.

Ces rencontres seront l'occasion de mieux nous connaître, d'échanger
entre pairs, de débattre ensemble et de surmonter les freins à la
contribution.

* « Qu'est-ce qu'on fabrique ?  Rencontre autour des projets des incubateurs numériques de plusieurs administrations publiques »
  SCHEDULED: <2018-11-29 jeu. 15:00-18:30>
  :PROPERTIES:
  :LOCATION: 20 avenue de Ségur, 75007 Paris
  :ID:       9c98501b-3d5c-4761-8a8e-3aad7581dc3a
  :END:

La fabrique numérique du ministère de la Transition écologique et
solidaire, l’incubateur de services numériques du ministère des
Armées, l'incubateur des ministères sociaux et les Entrepreneurs·e
d'intérêt généraux se réunissent pour présenter leurs projets.  Vous
êtes designer, développeur ou datascientiste pour l'administration
publique ?  Rejoignez-nous pour cet échange informel qu'on espère
instructif et constructif !

* Santé et numérique : quels enjeux éthiques ?
  SCHEDULED: <2018-11-19 lun. 9:00-13:00>
  :PROPERTIES:
  :LOCATION: Auditorium de l'Institut Imagine, 24 boulevard du Montparnase, Paris 15e
  :ID:       2d57b721-9278-4812-9985-3b95f375a023
  :END:

https://ccnecerna.sciencesconf.org/

Max Dauchet, Président de la CERNA
Jean-François Delfraissy, Président du CCNE
Stanislas Lyonnet, Directeur Général de l’Institut Imagine

Intervenants :

- Stéphanie Combes, rapporteur de la mission Health Data Hub,
  Ministère des Solidarités et de la Santé
- Sophie Crozier, membre du CCNE et coordinatrice pour l’AP-HP de la
  démarche éthique
- Jean-François Delfraissy, Président du CCNE
- Pierre-Henri Duée, membre du CCNE et président de la Section
  Technique du CCNE
- Christine Froidevaux, membre de la CERNA, professeure
  d’Informatique, Université Paris-Saclay
- David Gruson, Fondateur initiative Ethik IA, rapporteur du groupe de
  travail CCNE numérique & santé
- Claude Kirchner, membre du CCNE et de la CERNA, rapporteur du groupe
  de travail CCNE numérique & santé
- Jacques Lucas, Premier Vice-président du Conseil National de l'Ordre
  des médecins. Délégué Général au Numérique

* Données et éducation, comment mieux protéger pour mieux valoriser ?
  SCHEDULED: <2018-10-25 jeu. 18:00-20:00>
  :PROPERTIES:
  :LOCATION: Lab 110 bis, 54 rue de Bellechasse, 75007 Paris
  :ID:       c6161b49-49eb-451e-9e17-961302361339
  :END:

https://www.eventbrite.fr/e/billets-donnees-et-education-comment-mieux-proteger-pour-mieux-valoriser-51286311739

* Etalab Talk Pass culture à Ségur (salle 5.720)
  SCHEDULED: <2018-12-18 mar. 12:30-14:00>
  :PROPERTIES:
  :LOCATION: 20 avenue de Ségur, 75007 Paris
  :ID:       4d893e23-9b7d-470d-aa03-914723d66c3f
  :END:

* Etalab talk L. Maurel et L. Aufrère autour du Pass Culture
  SCHEDULED: <2018-12-18 mar. 12:30-14:00>
  :PROPERTIES:
  :LOCATION: 20 avenue de Ségur, 75007 Paris
  :ID:       ea189e03-9ce2-4518-83d3-ff10f1434f2c
  :END:

- [[gnus:nnimap+localhost:datagouv/INBOX#CADX00U+Gnk9A5pionNGJ8+=0=yysG53uP=w=x+ecGB9tF2dwgg@mail.gmail.com][from Lionel Maurel: Re: Etalab talk avec Lionel Maurel et Laura Aufrèr]]

* Soirée autour metada.org
  SCHEDULED: <2018-10-17 mer. 18:00>
  :PROPERTIES:
  :LOCATION: LLL, 16 Rue du Caire, 75002 Paris
  :ID:       42d5740b-3655-400c-9a9f-4009e33f2d30
  :END:

* Etalab talk d'Antoine Augusti sur Apache Airflow
  SCHEDULED: <2018-10-12 ven. 12:30-14:00>
  :PROPERTIES:
  :ID:       d03e7ff8-48c4-454c-8e2a-e32399cbb7c6
  :LOCATION: 20 avenue de Ségur, 75007 Paris
  :END:

RDV le 12 octobre de 12h30 à 14h en salle 5.720 pour un Etalab talk !

*Antoine Augusti*, ingénieur en informatique et actuellement EIG à la
Direction des Affaires Maritimes propose de s'intéresser aux problèmes
de transferts de données entre plusieurs sources et de modélisation de
dépendances entre tâches avec des pipelines.

Apache Airflow et Embulk permettent de modéliser des graphes de tâches
avec des dépendances entre elles, d'exécuter ces tâches, gérer les
logs et le monitoring, la qualité.  Si vous cherchez quelque chose de
plus robuste, sûr et explicable que les tâches CRON, ceci est pour
vous.

* Nuit du code citoyen
  :PROPERTIES:
  :ID:       78688cf1-1cca-4575-9a4e-6e3941e25025
  :END:
  <2018-03-09 ven.>-<2018-03-10 sam.>

http://nuitcodecitoyen.org

Les 9-10 mars prochain aura lieu La Nuit du Code Citoyen, un évènement
co-organisé par Latitudes, Les Bricodeurs et La Paillasse, et à
laquelle Étalab et EIG se joignent en tant que partenaires.  C'est un
hackathon de 24h non stop, où l'objectif est d'accélérer des projets
qui mêlent technologies avancées et impact social, grâce à la
mobilisation de citoyens qui ont des compétences tech, produit, UX,...

* Futur.e.s in Paris (Neuvième édition)
  :PROPERTIES:
  :ID:       96174856-e0c6-4410-a67b-a6c319b6c9c4
  :END:
  <2018-06-21 jeu.>-<2018-06-23 sam.>

https://mailchi.mp/futuresfestivals/futur-en-seine-devient-futures-2236121?e=f426646cdb

L'équipe EIG sera présente à Futur en Seine le vendredi.

* DataScience Summer School 2018
  :PROPERTIES:
  :ID:       fc28861b-2b12-48a7-bbea-4358b724e922
  :END:
  <2018-06-25 lun.>-<2018-06-29 ven.>

http://www.ds3-datascience-polytechnique.fr

* Intelligence artificielle et cognition : apprentissages naturels et artificiels (1/2)
  :PROPERTIES:
  :ID:       9f8738e1-63e6-4e06-84bd-eb404f6799c4
  :END:
  <2018-07-05 jeu. 08:45-12:30>
  :PROPERTIES:
  :LOCATION: 29 rue d'Ulm 75005 Paris
  :END:

Salle Jaurès

http://www.ens.fr/agenda/intelligence-artificielle-et-cognition/2018-07-05t064500

"L’intelligence artificielle (IA) entendue au sens large est au coeur
d’une révolution à la fois scientifique, technologique et
sociétale. Elle consiste à déployer à de grandes échelles des
algorithmes qui apprennent à simuler certaines fonctions cognitives,
et ambitionne parfois de remplacer l’humain dans de nombreuses tâches
nécessitant des fonctions cognitives supérieures (langage, perception,
action, décision, etc).

A quel point l’IA apporte-t-elle des modèles valides pour l’étude de
la cognition et de l’apprentissage? En quoi les données des sciences
cognitives peuvent-elles inspirer de nouveaux algorithmes? En quoi les
algorithmes qui remplacent l’humain sont-ils fiables? Quelles
conséquences pour l’imbrication de l’humain et de la machine dans la
société de demain?"

* Intelligence artificielle et cognition : apprentissages naturels et artificiels (2/2)
  :PROPERTIES:
  :ID:       c58c0463-20c1-4921-9b1a-d4e3037f3cf2
  :END:
  <2018-07-06 ven. 08:45-12:30>
  :PROPERTIES:
  :ID:       3aac9fb2-8a1c-4ab2-90b4-c307dd44c748
  :LOCATION: 29 rue d'Ulm 75005 Paris
  :END:

http://www.ens.fr/agenda/intelligence-artificielle-et-cognition/2018-07-05t064500

* https://www.numerique-en-commun.fr
  :PROPERTIES:
  :LOCATION: Nantes
  :ID:       cf366db9-c6f6-48b5-8bac-f0f5a6fd2337
  :END:
  <2018-09-13 jeu.>-<2018-09-14 ven.>

Propulsées par la Mednum et la Mission Société Numérique, accueillies
par le Conseil Départemental de Loire-Atlantique, Nantes Métropole, et
animées par l’association PiNG, les 5èmes rencontres nationales de la
médiation et des cultures numériques se dérouleront les 13 et 14
septembre 2018 à Nantes durant la Nantes Digital Week.

Les acteurs de la médiation et des cultures numériques proposent
durant deux jours des parcours thématiques, ateliers, master class,
prototypes et conférences.

L’objectif commun : partager des approches innovantes, soutenables et
durables des cultures numériques et croiser les expériences au service
des transitions.

* Journées plénières du GDR IA : 2-3 Octobre 2018 - Paris
  :PROPERTIES:
  :LOCATION: Paris
  :ID:       a57b7402-f057-4c4d-b664-657f8ecb4e45
  :END:
  <2018-10-02 mar.>-<2018-10-03 mer.>

Les journées plénières du GDR IA (http://www.gdria.fr/) auront lieu
les 2 et 3 octobre à Paris (Université Paris Dauphine). Elles seront
centrées sur des exposés invités sur les thématiques des groupes de
travail du GDR:

- Contraintes et Apprentissage,
- Jeux, 
- Planification Multi-Agents, Flexible, Temporelle, Epistémique et Contingente, 
- Médiation 
- Représentations et Algorithmes en Pratique, 
- Explicabilité

ainsi que sur les activités des groupes de travail inter-GDR:

- Raisonner sur les Données (avec le GDR Madics) 
- Théorie Algorithmique de la Décision et des Jeux (avec le GDR RO)

Des sessions de discussion seront également organisées.

* Océan Hackathon
  :PROPERTIES:
  :ID:       183e6c18-c7e7-42d6-b85c-ba90766e3c88
  :END:
  <2018-10-05 ven.>-<2018-10-07 dim.>

- Page d'accueil : https://www.facebook.com/OceanHackathon/
- Pourquoi déposer son défi : https://www.youtube.com/watch?v=Il66DecTLNY

Les EIG des défis B@liseNav et Prédisauvetage participent.

* www.dataliteracyconference.net #DLC2018
  :PROPERTIES:
  :LOCATION: Aix-en-Provence
  :ID:       00208cf1-4f9e-4525-a1f2-d547664d1c89
  :END:
  <2018-10-05 ven.>-<2018-10-06 sam.>

Si les « data » sont aujourd’hui un puissant vecteur de développement
économique, de capacitation citoyenne ou encore, de production de
connaissances, elles suscitent également des inquiétudes légitimes,
ainsi que des luttes de pouvoir. L’idée montante d’une « littératie »
des données consiste à permettre à tout décideur, collaborateur,
innovateur, entrepreneur, chercheur ou citoyen d’en comprendre les
enjeux, d’en discuter les sources et les usages, et d’en tirer parti
dans sa propre activité.
                                                                                     
Dans les entreprises et les administrations, à l’école, dans la
recherche comme dans la société, la capacité de produire, comprendre
et utiliser des données numériques devient une compétence
essentielle. Avec les meilleurs experts mondiaux et après le succès
des éditions 2016 et 2017, Data Literacy Conference 2018 délivre les
clés d’une « culture de la donnée » enfin accessible aux
non-spécialistes.

* OceanHackathon (ENSTA-Bretagne)
  :PROPERTIES:
  :ID:       44e2c068-8f17-4578-98ab-a6af83d57167
  :END:
  <2018-10-05 ven.>-<2018-10-07 dim.>

https://www.facebook.com/OceanHackathon/

http://www.tech-brest-iroise.fr/Actualit%c3%a9s-Ocean-Hackathon-_3-du-5-au-7-octobre-2018-%c3%a0-l%e2%80%99ENSTA-Bretagne-2124-2807-0-0.html

* COMMENT Configuration

#+SEQ_TODO:  STRT(s) NEXT(n) TODO(t) WAIT(w) | DONE(d) CANCELED(c)
#+LANGUAGE:  fr
#+DRAWERS:   HIDE LOGBOOK
#+ARCHIVE:   ~/.eig2/archives/eig-open-agenda-archives.org::
#+CATEGORY:  EIG
* HackEdu - pendant le salon EducaTice
  :PROPERTIES:
  :ID:       71f042fb-0892-4ccd-95f2-2ff88f9ba208
  :END:
  <2018-11-21 mer.>-<2018-11-23 ven.>

Un Hackathon sur trois jours autour des données pédagogique, organisé
par le Ministère de l'Éducation National.

Les EIG du défi CoachÉlèves participent.

* Éditathon Wikipédia aux Gobelins
  SCHEDULED: <2018-09-21 ven.>
  :PROPERTIES:
  :ID:       02794dc4-5e0d-4192-8561-b032d90bfa6c
  :END:

Visite des ateliers des Gobelins le matin et enrichissement de
contenus et d'articles sur les projets Wikimédia l'après-midi.

Inscription libre et gratuite : bastien.guerry AT data.gouv.fr

* Projection du documentaire « Datagueule Démocraties »
  SCHEDULED: <2018-09-19 mer. 18:30>
  :PROPERTIES:
  :ID:       24cae33b-77db-40a5-bb99-5d246a31a9a2
  :END:

A l’initiative de Victor Schmidt, une projection du documentaire
Datagueule – Démocraties, le mercredi 19/09 au Liberté Living Lab, en
présence des réalisateurs, dont Sylvain Lapoix.

* Étalab talk sur « Le Drenche » à Ségur salle 4.724
  SCHEDULED: <2018-09-14 ven. 12:30-14:00>
  :PROPERTIES:
  :LOCATION: 20 avenue de Ségur, 75007 Paris
  :ID:       d4a804d3-8a7a-40f7-8072-d97420193345
  :END:

Avec F. Guignard et J. Cagé.

* Étalab talk sur NosSystèmes - transparence et jouabilité des données
  SCHEDULED: <2018-07-11 mer. 12:30-14:00>
  :PROPERTIES:
  :ID:       638c6e40-47d2-4de0-b329-27e78864d6ee
  :END:

NosSystèmes : Objectif de cette nouvelle saison NosSystèmes : rendre
les algorithmes publics plus intelligibles, joignables, jouables,
symétriques et ouverts. Après une première année de collaboration avec
Etalab sur la plateforme APB, nous allons dans cette nouvelle séquence
explorer de nouveaux terrains, choisis dans le vivier des projets EIG
et des Startups d’Etat, et travailler avec eux et nos partenaires à
rendre les algorithmes publics toujours plus exemplaires.  Loup
Cellard : Loup Cellard est designer et doctorant au Centre For
Interdisciplinary Methodologies de l'Université de Warwick (UK).

Dans le cadre de cette thèse, il réalise une enquête à Etalab autour
de l'ouverture des algorithmes publics et de la place du design dans
les projets de transparence démocratique.L'idée pendant ce dej serait
de se familiariser avec les deux démarches et de continuer la
collaboration avec eux après l'été pour les EIG intéressés.

* Fab14+ (tout juillet 2018)
  SCHEDULED: <2018-07-01 dim.>
  :PROPERTIES:
  :ID:       af28610e-eeec-418d-8672-14a950e295e7
  :END:

http://www.fab14.org/fr/fab14-plus/

* Événement Villani/Mounir/Delli au LLL
  SCHEDULED: <2018-06-28 jeu. 14:00-19:00>
  :PROPERTIES:
  :ID:       93955e1e-8691-4e7c-83f1-6a77eb2a49f7
  :LOCATION: 9 rue d'Alexandrie, 75002 Paris
  :END:

https://www.eventbrite.com/e/revolutions-de-lia-enjeux-tech-enjeux-de-societe-tickets-46715235527

The Future Society et le Liberté Living Lab co-organisent le jeudi 28
juin après-midi (13h > 20h) des ateliers thématiques sur le thème de
l’intelligence artificielle.

Le but de cet après-midi est de permettre aux participants de mieux
s’approprier les enjeux de la montée en puissance de l’IA. Le format
des débats sera donc très participatif, notamment sous la forme
d’ateliers thématiques. Cet après-midi sera ponctué par une
table-ronde et débat en plénière en présence de Cédric Villani, député
de LaREM de la 5ème circonscription de l'Essonne, Vice-Président de
l'Office Parlementaire pour l'Évaluation des Choix Scientifiques et
Technologiques (OPECST), Karima Delli, député européenne et Présidente
de la Commission des Transports, André Loesekrug-Pietri, porte-parole
de Joint European Disruptive Innovation (J.E.D.I) et Khalil Rouhana,
Directeur Général Adjoint de DG Connect.

* Session Tech EIG / Front & Back End
  SCHEDULED: <2018-06-27 mer. 13:00-14:30>
  :PROPERTIES:
  :LOCATION: Liberté Living Lab, 9 rue d'Alexandrie 75002 Paris
  :ID:       a7705bf0-7893-4098-8343-24697938c2bd
  :END:

- Intro à GraphQL par Stanislas Chollet, Engineering Manager / Lead
  Core API @ Dailymotion.

  GraphQL est une alternatives aux API REST utilisé notamment par
  Github et Facebook.  Quant à Stan, c'est un passionné d'informatique
  et fervent adepte de GraphQL, il présente régulièrement à différents
  meetup et conférences que ce soit sur GraphQL, Kubernetes du côté
  developeur ou l'automatisation en général: vous en trouverez plus
  sur lui ici.

- Une présentation "front" (React.js, du one action per screen,
  progressive web apps, server side rendering) à préciser en fonction
  des participants par Loick Le Digabel, Lead Front Engineer @
  Blablacar.

  Après avoir travaillé sur du front classique chez Dailymotion et
  participé à leur premier POC avec React.js, Loick a mis en place
  toute la nouvelle architecture front de Blablacar et vient partager
  avec nous ses retours d'expérience.  Probablement pas de 3e speaker
  pour laisser du temps au public et aux intervenants d'échanger
  autour des projets de chacun ! :)

Les détails logistiques :

- mercredi 27 juin 2018
- 13h à 14h30
- Liberté Living Lab, 9 rue d'Alexandrie 75002 Paris

* Journée wiki·data·gouv à la DINSIC
  SCHEDULED: <2018-06-12 mar.>
  :PROPERTIES:
  :CAPTURED: [2018-05-07 lun. 09:45]
  :ID:       e43e3918-bc06-4de9-bdb3-1db20b719e90
  :LOCATION: 20 avenue de Ségur, 75007 Paris
  :END:

Détails : https://github.com/etalab/wiki-data-gouv

De 9h30 à 18h30

À la DINSIC, salle 5.728 au 20 avenue de Ségur 75007 Paris.

* Mapathon Missing Maps Paris @ La Paillasse
  SCHEDULED: <2018-06-06 mer. 18:30-21:30>
  :PROPERTIES:
  :LOCATION: 226 Rue Saint-Denis, 75002 Paris
  :ID:       6822f5f2-ab0e-4a9c-919c-d69db7b05552
  :END:

   Venez nous aider à cartographier sur OpenStreetMap, la carte du
   monde collaborative et libre
                                                                                           
   CartONG et La Paillasse vous invitent à un mapathon pour découvrir
   la cartographie participative et humanitaire dans OpenStreetMap :
   pas besoin d'être un expert, c'est accessible à tout le monde !

   https://www.eventbrite.ca/e/billets-mapathon-missing-maps-paris-la-paillasse-46315029500
                                                                                           
* Rencontres Internationales de la Gestion Publique
  SCHEDULED: <2018-06-06 mer. 09:00-17:30>
  :PROPERTIES:
  :LOCATION: 139, rue de Bercy Centre de conférences Pierre-Mendès-France - 75012 Paris
  :ID:       3d3f67d0-0969-4704-b7b5-b9a7306856e2
  :END:

Le code a changé - Quelle gouvernance de l'action publique à l'ère
numérique ?

Lieu : 139, rue de Bercy Centre de conférences Pierre-Mendès-France -
75012 Paris

https://www.economie.gouv.fr/igpde-seminaires-conferences/rencontres-internationales-gestion-publique-rigp

* Étalab talk avec Dario Taraborelli salle 5.728 de 12h30 à 14h00
  SCHEDULED: <2018-06-04 lun. 12:30-14:00>
  :PROPERTIES:
  :LOCATION: 20 avenue de Ségur, 75007 Paris
  :ID:       ff866ecf-0574-4c88-b53f-07ce62b3c036
  :END:

Dario Taraborelli est directeur de la recherche de la fondation
Wikimédia.

Salle 5.728 de 12h30 à 14h00

*Title:* Supporting free knowledge with research and open data

*Abstract:* At the Wikimedia Foundation, we use data and open source
technology to understand and empower millions of readers and
contributors who interact with Wikipedia and its sister projects on a
daily basis. In this talk I’ll give an overview of the research team’s
current priorities and how we work to make our output reusable and
reproducible. I’ll focus in particular on an initiative called
WikiCite, aiming to improve our understanding of where Wikipedia and
Wikidata get their information from, by building a comprehensive,
collaboratively edited, structured knowledge base of citable sources
in Wikidata.

* Open Talk DINSIC sensibilisation à l'accessibilité numérique
  SCHEDULED: <2018-05-25 ven. 12:00-14:00>
  :PROPERTIES:
  :LOCATION: 20 avenue de Ségur, 75007 Paris
  :ID:       96a8d950-40a0-46f7-b6a9-316526706d73
  :END:

Opentalk DINSIC vendredi 25 mai à Ségur en salle 5.723 de 12h à 14h.

Prévoir son sandwich.

* L'IA : enjeux et défis pour la transition écologique et énergétique
  SCHEDULED: <2018-05-25 ven. 11:00-12:30>
  :PROPERTIES:
  :LOCATION: Auditorium de la tour Séquoia
  :ID:       9eeb95a4-9f25-466e-9e2e-9c2ea32528b6
  :END:

- Intervenants de la mission Villani
- https://eig-hq.slack.com/messages/C859D1X41/files/FARCV3ZRQ/

* Démocratie(s) ? #DataGueule // Projection et world Café
  SCHEDULED: <2018-05-24 jeu. 18:45-22:00>
  :PROPERTIES:
  :LOCATION: 23 Rue Dagorno, 75012 Paris
  :ID:       c1a7183f-58d2-42ab-a425-4488d6b6c668
  :END:

- L’arsenal - Le Tiers-Lieu Des Associations Étudiantes
- https://www.facebook.com/events/1757314807661581/permalink/1759906360735759

* Étalab talk (en français) sur « The Mother of All Demos » (Douglas Engelbart, 1968)
  SCHEDULED: <2018-05-04 ven. 12:00-14:00>
  :PROPERTIES:
  :ID:       f2a4e922-4445-4b2b-b0c0-9a4268f7c17d
  :LOCATION: 20 avenue de Ségur, 75007 Paris
  :END:

Animé par C. Quest et B. Guerry.

http://dougengelbart.org/firsts/1968-demo-interactive.html

Nous diffuserons la vidéo et commenterons le contexte technique de
1968, avec un focus particulier sur Stewart Brand, dont l’histoire
est racontée dans l’ouvrage de [[https://cfeditions.com/utopieNumerique/][Fred Turner, Aux sources de l’utopie
numérique]], 2012.

* La mobilité de la filière numerique au sein de l'État
  SCHEDULED: <2018-05-03 jeu.>
  :PROPERTIES:
  :ID:       7008d206-c97d-4cf9-b082-cf24a4f7b961
  :END:

https://www.fonction-publique.gouv.fr/mobilitensic2018

* Disruptions publiques - Saison 1 : La Blockchain 
  SCHEDULED: <2018-04-27 ven. 14:00-17:30>
  :PROPERTIES: 
  :LOCATION: 69 Rue de Varenne, Paris 75007
  :ID:       55d0e640-97c0-4080-b644-db4432935f50
  :END:

Au programme : une session découverte et inspiration avec les
programmes blockchain de la Caisse des Dépôts et Consignations, puis
un atelier d’idéation. En compagnie de Nadia Filali Directrice des
Programmes blockchain et pilote de LabChain, et Pierre Noro chargé
d’innovation blockchain à la Caisse des Dépots et
Consignations. L'évènement se déroulera le 27 avril de 14h à 17h au 69
rue de Varenne.

Inscription via ce lien: https://bit.ly/2HCLART

* Petit déjeuner de l’innovation autour de l’IA à travers une conférence de Frédéric Wickert
  SCHEDULED: <2018-04-12 jeu. 09:15>
  :PROPERTIES:
  :LOCATION: 40 rue de la Victoire 75009 Paris
  :ID:       998d8c59-c112-4271-b4a6-26aaf5afa317
  :END:

Kicklox organise le 12 Avril à 9h30 un petit déjeuner de l’innovation
autour de l’IA à travers une conférence de Frédéric Wickert –
Technical Evangelist chez Microsoft.

Inscription via ce lien : https://bit.ly/2pS6Jjg

* GAFAM, BATX : que valent nos données personnelles ? »
  SCHEDULED: <2018-04-09 lun. 19:15-21:15>
  :PROPERTIES:
  :LOCATION: Amphithéâtre Emile Boutmy - 27 rue Saint-Guillaume 75007 Paris
  :ID:       35f36326-9daf-4956-a145-a9adea276cf2
  :END:

https://www.sciencespo.fr/evenements/?event=gafam-batx-que-valent-nos-donnees-personnelles

Dans le cadre des Rencontres de Bioéthique de Sciences Po, conférence avec :

- Dominique Cardon, directeur du médialab de Sciences Po, professeur
  de Sociologie

- Christine Froidevaux, vice-présidente de la Société informatique de
  France, professeur d’informatique, Université Paris-Sud-Paris-Saclay

- Claude Huriet, sénateur honoraire, membre honoris causa de
  l’Académie nationale de médecine.

Présentation du débat par Emmanuel Hirsch, professeur à l’Université
Paris-Sud-Paris-Saclay, directeur de l’Espace éthique d’Ile-de-France.

* Hands-on chatbot
  SCHEDULED: <2018-04-09 lun. 19:00>
  :PROPERTIES:
  :LOCATION: Google France 38 avenue de l'Opéra Paris
  :ID:       fc564609-1fb7-4c60-b4dd-3db92e76781b
  :LOCATION: 20 avenue de Ségur, 75007 Paris
  :END:

- https://www.meetup.com/fr-FR/Duchess-France-Meetup/events/248991072/

* Étalab talk (en anglais) sur l’open source chez AWS
  SCHEDULED: <2018-04-06 ven. 12:30-14:00>
  :PROPERTIES:
  :ID:       120bd257-d301-422a-a996-e0c19814189f
  :END:

Rencontre avec Z. [[https://www.linkedin.com/in/zaheda-bhorat-143121][Bhorat]], en charge de la stratégie open-source
d'Amazon Web Services.

L'etalab talk se fera en anglais.

* Conférence de Yann Lecun
  SCHEDULED: <2018-04-04 mer. 18:30>
  :PROPERTIES:
  :LOCATION: BnF, Paris
  :ID:       1b035827-5670-4af6-840c-e44be845704d
  :END:

La théorie de l'apprentissage de Vapnik et les progrès récents de
l'intelligence artificielle.

http://smf.emath.fr/content/conf%C3%A9rence-bnf-yann-le-cun

* Garagethon Storia
  SCHEDULED: <2018-03-30 ven. 09:30-18:00>
  :PROPERTIES:
  :LOCATION: Liberté Living Lab
  :ID:       4d65f0eb-f34b-4434-aca9-e1d0c733a2f6
  :END:
* Sommet intelligence artificielle - ai-for-humanity
  SCHEDULED: <2018-03-29 jeu. 08:00-14:00>
  :PROPERTIES:
  :ID:       f5937acb-ddf2-4d23-9332-f2efaf29f75c
  :END:

https://www.numerique.gouv.fr/ai-for-humanity

* Esthétique des données - Gaîté Lyrique
  SCHEDULED: <2018-03-01 jeu. 19:00>
  :PROPERTIES:
  :ID:       6446ff51-ce32-4523-973f-1b2133e123d3
  :END:

https://gaite-lyrique.net/esthetique-des-donnees

* Perspectives de l’IA
  SCHEDULED: <2018-02-27 mar. 18:00-20:00>
  :PROPERTIES:
  :ID:       a4aef00b-46ae-4b60-9180-c5c7a2d5c9e8
  :END:

Perspectives de l’IA dans le secteur public autour du rapport de
Jérôme Pesenti

Amphithéâtre Leroy-Beaulieu-Sorel - 27 rue Saint-Guillaume, 75007
Paris.

https://www.sciencespo.fr/evenements/?event=perspectives-de-lia-dans-le-secteur-public-autour-du-rapport-de-jerome-pesenti

* MakeryMedialab #3 Que partage-t-on dans les Fablabs?
  SCHEDULED: <2018-02-22 jeu. 19:00>
  :PROPERTIES:
  :ID:       587bcd3e-7e15-48c1-b7f6-d8a13ba461b6
  :END:

Lieu : Gaîté Lyrique

